name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    # Eğer projen android/ klasöründeyse bu 4 satırı aç:
    #defaults:
    #  run:
    #    working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Gradle'ı wrapper olmadan kullan
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: zizu-debug-apk
          # Proje kökteyse bu yol çalışır; alt klasördeyse başına klasör adını ekle
          path: app/build/outputs/apk/debug/*.apk

          defaults:
  run:
    working-directory: android

