name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: android   # <-- ANDROID KLASÖR ADIN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute for gradlew
        run: git update-index --chmod=+x gradlew

      - name: Build Debug APK
        run: .\gradlew.bat assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: zizu-debug-apk
          path: app/build/outputs/apk/debug/*.apk
